#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' ignore-parents parent pwd

hash -d diss=~/Documents/Uni/CERN/Dissertation
hash -d gmt=~diss/vhdl/GMT

source $HOME/.aliases
bash $HOME/dotFiles/check_kerberos.sh

export EDITOR=vim
export VISUAL=vim

export LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s"
export LESS=' -R '

eval "$(thefuck --alias damn)"

